### ISSUE TITLE
Order Id mismatch

### ISSUE THREAD

**Issue by jgermade** [aplazame/magento#12]
Articles Id in admin list and checkout json data doesn't match.

![pasted image at 2016_08_04 18_44](https://cloud.githubusercontent.com/assets/2305833/17410750/5ec27156-5a75-11e6-9cc1-9013442111fc.png)
![pasted image at 2016_08_04 18_43](https://cloud.githubusercontent.com/assets/2305833/17410756/63a8c440-5a75-11e6-9521-99b53f156231.png)

For product with sku 'msj006c-Royal Blue-L', the id in admin is 905 and 598 in checkout data.

**Comment by Maks3w** [comment]
Fixed

**Comment by jgermade** [comment]
Still having same error on magento-dev.aplazame.com

**Comment by Maks3w** [comment]
Not reproduced
