### ISSUE TITLE
Excepción al cancelar

### ISSUE THREAD

**Issue by alexsancho** [aplazame/magento#14]
Tal y como está escrito el módulo, es imposible cancelar un pedido que tenga aplazame como método de pago si el pedido no está registrado en el sistema de aplazame.

La api devuelve un error y el proceso de cancelación se ve interrumpido, sugiero cambiar esta lógica de forma que no devuelva una excepción.

**Comment by alexsancho** [comment]
estoy investigando el código que se encarga de cancelar la orden y he llegado hasta este método (1) que no estoy seguro de que hace, parece una lógica errónea, en las pruebas que he realizado la id nunca tiene un dash (-) por lo que la $nextOrder nunca se carga y php lanza un warning porque $orderId[1] no existe.

¿para que esta esta condición aquí?

1-  https://github.com/aplazame/magento/blob/master/extension/app/code/community/Aplazame/Aplazame/Model/Observer.php#L69-L77

**Comment by Maks3w** [comment]
Cuando editas una orden magento cancela la orden original y crea una nueva con ese formato.

En general `$nextOrder->getId()` siempre es evaluado como `false`, se puede considerar que quien escribió ese fragmento quizás lo hizo para prevenir condiciones de carrera.

**Comment by Maks3w** [comment]
He publicado la versión v3.0.2 que corrige el acceso a $orderId[1] y que también silencia el error cuando la orden todavía no existe en Aplazame.

https://s3.eu-central-1.amazonaws.com/aplazame/modules/magento/Aplazame_Aplazame-0.3.2.tgz
