### ISSUE TITLE
Cancelar pedido

### ISSUE THREAD

**Issue by alexsancho** [aplazame/magento#16]
Los pedidos que se realizan con aplazame no se pueden cancelar en el backend de magento, tengo dos casos concretos, el primero no se ha registrado en aplazame y en magento aparece como pendiente, al intentar cancelar solo devuelve un mensaje de "no se ha podido cancelar" en el segundo caso se ha cancelado el pedido en el backend de aplazame, en magento ha quedado como pedido en curso sin la posibilidad de cancelar o reembolsar, el error al reembolsar es que "no se ha podido crear la nota de crédito"

**Comment by Maks3w** [comment]
Hola @alexsancho 

  ¿Puedes decirnos qué versión del plugin estás utilizando? Ayer mismo liberamos la versión v0.4.0 que contiene arreglos en este aspecto.

Saludos.

**Comment by alexsancho** [comment]
acabo de instalar la última del repositorio, que por cierto arregla un bug que estaba ocurriendo en nuestra tienda por el que se lanzaba la petición a la api sin enviar las credenciales

**Comment by Maks3w** [comment]
Sólo por aclarar el contexto,

¿Este bug te sucede con la versión v0.4.0 y también con las versiones anteriores?

Gracias.

**Comment by alexsancho** [comment]
sucede con la actual (v0.4.0), no te puedo confirmar que sea exactamente lo mismo que con las anteriores, aunque con las anteriores tampoco podía cancelar los pedidos.

**Comment by Maks3w** [comment]
¿Puedes indicarnos si en los [logs de Magento](http://www.inmotionhosting.com/support/edu/magento/203-troubleshooting-magento/enabling-system-and-exception-logging-in-magento) aparece alguna entrada a la hora que realizaste la acción?

**Comment by Maks3w** [comment]
La última versión del módulo tiene un flag que permite distinguir entre devoluciones offline y online cuando autoinvoice está activo.

Si puedes pruébalo y nos comentas en soporte@aplazame.com si te funciona como esperas.
