### ISSUE TITLE
Título del método

### ISSUE THREAD

**Issue by alexsancho** [aplazame/magento#18]
La extensión resetea el título del metodo en la línea 17 de magento/extension/app/code/community/Aplazame/Aplazame/Block/Payment/Form.php

Esto rompe el layout cuando no se está utilizando el chekout de magento, en nuestro caso IWD One Page Checkout, sugiero cambiar este comportamiento, añadiendo la posibilidad de definir el contenido del título desde el backend.

**Comment by Maks3w** [comment]
Gracias, tomo nota y revisaré la integración de nuestro plugin con ese checkout que comentas.

**Comment by Maks3w** [comment]
Así es como se ve actualmente

Ventana ancha:
![image](https://cloud.githubusercontent.com/assets/1301698/20601243/e531e840-b257-11e6-82a0-aa56597aa675.png)


Ventana estrecha: 
![image](https://cloud.githubusercontent.com/assets/1301698/20601230/d777195a-b257-11e6-9aae-e35f960ba319.png)

Ventana muy estrecha:
![image](https://cloud.githubusercontent.com/assets/1301698/20601262/ffbfc7f4-b257-11e6-9fee-0a344026dc3e.png)
