### ISSUE TITLE
Servir los recursos comprimidos

### ISSUE THREAD

**Issue by informundo** [aplazame/magento#19]
Los recursos son servidos sin habilitar la compresión lo que hace mas lenta la página. En las páginas que no figura el simulador como las categorias, cms, etc.. solo carga 1 .js lo que la hace un poco mas lente (image1.png), pero en las que debe cargar el simulador que carga varios recursos (image2.png) la hace mucho mas lenta, hasta 10 puntos en el test de PageSpeed Insights.
Un saludo,
Marcos
![image1](https://cloud.githubusercontent.com/assets/8274587/21954087/20478ef4-da48-11e6-82ae-983b53a84625.png)
![image2](https://cloud.githubusercontent.com/assets/8274587/21954088/204b3ff4-da48-11e6-9e7a-0608d0727072.png)

**Comment by Maks3w** [comment]
Muchas gracias por tu sugerencia. Se lo traslado al equipo que lleva el JS para que lo tengan en cuenta.
