### ISSUE TITLE
código "desde 0,00€/mes"

### ISSUE THREAD

**Issue by aritzlp** [aplazame/magento#20]
Hay una función del aplazame que te pone según el total cuánto sería al mes, pero al ponerte el millares no se hacen bien los cálculos.
![desde-x-mes](https://user-images.githubusercontent.com/32059519/30537746-444d9baa-9c6b-11e7-80e9-7ab4d0ffeb3e.jpg)
Dónde se puede mirar esto???

Otra cosa, para ponerle el icono de la A en "desde 0,00€/mes" dónde está esa parte del código???

PD: es la primera vez que utilizo github y no sé si esta clase de preguntas se pueden hacer aquí

Un saludo

**Comment by Maks3w** [comment]
Buenas tardes,

   El número no está en un formato de millares adecuado (no se puede interpretar el signo de espacio como un separador de millares válido)

  En su lugar te recomendamos que adaptes tu página al formato de microdatos propuesto por Schema.org y adaptes el selector del precio.

Saludos.
